/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import modelo.Producto;

/**
 *
 * @author DELL
 */
public class BuscarProducto extends javax.swing.JFrame {
    private int estado = 0;
    private Producto producto = null;
    private DefaultListModel<String> modeloNombres;
    private DefaultListModel<String> modeloCodigos;
    private List<String> listaNombres;
    private List<String> listaCodigos; // Lista para códigos

    public BuscarProducto() {
        initComponents();
        inicializarModelo();
        agregarListener();
    }

    private void inicializarModelo() {
        // Inicializa la lista de nombres y códigos y los modelos
        listaNombres = new ArrayList<>();
        listaNombres.add("andres");
        listaNombres.add("jant");
        listaNombres.add("antonio");
        listaNombres.add("albaro");

        listaCodigos = new ArrayList<>();
        listaCodigos.add("P001");
        listaCodigos.add("P002");
        listaCodigos.add("P003");
        listaCodigos.add("P004");
        listaCodigos.add("P015");
        listaCodigos.add("P014");

        modeloNombres = new DefaultListModel<>();
        for (String nombre : listaNombres) {
            modeloNombres.addElement(nombre);
        }
        liNombresProductos.setModel(modeloNombres);

        modeloCodigos = new DefaultListModel<>();
        for (String codigo : listaCodigos) {
            modeloCodigos.addElement(codigo);
        }
        liCodigosProductos.setModel(modeloCodigos);
    }

    private void agregarListener() {
        txtNombreProducto.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarListaNombres();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarListaNombres();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarListaNombres();
            }
        });

        txtCodigoProducto.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                filtrarListaCodigos();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                filtrarListaCodigos();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                filtrarListaCodigos();
            }
        });
    }

    private void filtrarListaNombres() {
        String textoBusqueda = txtNombreProducto.getText().toLowerCase();
        modeloNombres.clear(); // Limpiar el modelo actual

        for (String nombre : listaNombres) {
            if (nombre.toLowerCase().startsWith(textoBusqueda)) {
                modeloNombres.addElement(nombre); // Agregar nombres que coinciden
            }
        }
    }

    private void filtrarListaCodigos() {
        String textoBusqueda = txtCodigoProducto.getText().toLowerCase();
        modeloCodigos.clear(); // Limpiar el modelo actual

        for (String codigo : listaCodigos) {
            if (codigo.toLowerCase().startsWith(textoBusqueda)) {
                modeloCodigos.addElement(codigo); // Agregar códigos que coinciden
            }
        }
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tbtCambiar = new javax.swing.JToggleButton();
        laNombre = new javax.swing.JLabel();
        lsCodigo = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        liNombresProductos = new javax.swing.JList<>();
        btnEnterNombre = new javax.swing.JButton();
        btnEnterCodigo = new javax.swing.JButton();
        txtCodigoProducto = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        liCodigosProductos = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Busqueda del producto");
        jLabel1.setMaximumSize(new java.awt.Dimension(80, 40));
        jLabel1.setPreferredSize(new java.awt.Dimension(80, 40));

        tbtCambiar.setText("Cambiar");
        tbtCambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtCambiarActionPerformed(evt);
            }
        });

        laNombre.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        laNombre.setText("Por Nombre:");

        lsCodigo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lsCodigo.setText("Por Codigo:");

        txtNombreProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoActionPerformed(evt);
            }
        });

        liNombresProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(liNombresProductos);

        btnEnterNombre.setText("Enter");
        btnEnterNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterNombreActionPerformed(evt);
            }
        });

        btnEnterCodigo.setText("Enter");

        txtCodigoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodigoProductoActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(liCodigosProductos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(laNombre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEnterNombre)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNombreProducto, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(lsCodigo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCodigoProducto)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnEnterCodigo)
                        .addGap(8, 8, 8)))
                .addGap(53, 53, 53))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(tbtCambiar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tbtCambiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laNombre)
                    .addComponent(lsCodigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnterNombre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtCodigoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEnterCodigo)))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbtCambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtCambiarActionPerformed
        if (estado == 0) {
            this.estado = 1;

            btnEnterNombre.setEnabled(false);
            btnEnterCodigo.setEnabled(true);
            
        } else {
            this.estado = 0;

            btnEnterNombre.setEnabled(true);
            btnEnterCodigo.setEnabled(false);
        }

    }//GEN-LAST:event_tbtCambiarActionPerformed

    private void txtCodigoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoProductoActionPerformed

    private void txtNombreProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoActionPerformed

    private void btnEnterNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterNombreActionPerformed
        String nombre = txtNombreProducto.getText();
        
        EditarProducto ep = new EditarProducto();
        ep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEnterNombreActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnterCodigo;
    private javax.swing.JButton btnEnterNombre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel laNombre;
    private javax.swing.JList<String> liCodigosProductos;
    private javax.swing.JList<String> liNombresProductos;
    private javax.swing.JLabel lsCodigo;
    private javax.swing.JToggleButton tbtCambiar;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtNombreProducto;
    // End of variables declaration//GEN-END:variables
}
